### ISSUE TITLE
在Ubuntu18.04下初始化脚本执行出错

### ISSUE THREAD

**Issue by MengShaoying** [smarty-kiki/api_frame#1]
![image-1](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fy0hqc1aifj31000ed0vt.jpg)
![image-2](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fy0hs6i8qnj30m80e50u3.jpg)

**Comment by smarty-kiki** [comment]
感谢测试，在这个提交中修复了该问题
https://github.com/smarty-kiki/api_frame/commit/2e91cc2067ed4354611f81785db84618965646b1
